name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Volta
        uses: volta-cli/action@v1
        with:
          version: '1.0.0'

      - name: Install Node.js and npm with Volta
        run: volta install node@20.15.1 npm@10.8.0

      - name: Install Dependencies
        run: npm ci

      - name: Run Test
        run: npm run test